### ISSUE TITLE
Negotiation of generic packetizer

### ISSUE THREAD

**Issue by youennf** [murillo128/codec-agnostic-rtp-payload-format#1]
A generic packetizer is expected to replace codec-specific packetizers for H264, VP8, VP9...
It is important to make sure sender and receiver are on the same page.
A few options are available:
1. Use SDP for negotiation. For instance use a:rtpmap with a 'generic' string instead of VP9.
2. Use generic packetizer/depacketizer if a particular header extension (frame marking header extension) is being negotiated.
3. No SDP negotiation at all. Instead rely on a global switch like proposed for cryptex and have it globally set in RTCPeerConnection.

Option 1 might be a bit disruptive to existing applications.
Also it is not very consistent with how this is being done with audio.

Option 2 probably makes sense since there is a good chance that a generic packetizer also requires a way to expose frame metadata as a RTP header extension.

Option 3 is probably the simplest one. It is not as flexible as the others but there might be no need for m-sections with both legacy and generic packetizers, or a mix of generic/legacy packetizers on sender/receiver sides.
I would tend to go with option 3.

**Comment by murillo128** [comment]
I feel that not negotiating it on the SDP would be too hacky and not likely be accepted by the group.  I would expand the option 1 choices:

1a.- Negotiate it associated to each payload type. This would associate an extra PT to each codec PT negotiated on the SDP:
```
a=rtpmap:96 vp9/90000
a=fmtp:96 profile-id=0
a=rtpmap:97 generic/90000
a=fmtp:97 apt=96
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=96
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=97
``` 
The vp9 codec will be negotiated normally in SDP, and optionally, the generic packetization can be also be negotiated. This means that for example if a vp9 codec format is rejected (for example not supported profile-id), the generic one would also be discarded (which is good). However, this would require to have 2 more PTs per codec (one for the generic packetizer and another for the RTX), which could cause issues.

1b- Negotiate a single PT for the generic payload type and reference the original PT on the rtp packet.
```
a=rtpmap:96 vp9/90000
a=rtpmap:97 vp8/90000
a=rtpmap:98 generic/90000
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=96
a=rtpmap:100 rtx/90000
a=fmtp:100 apt=97
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=98
``` 
This would still require to negotiate the codecs normally in the SDP and would just two new PTs. Also, it would not be possible to remove the generic packetization for some codecs while keeping it for others. The caveat is that we would need to reference the original PT in either the payload or in a new header extension ( RED won't work if using it on a header extension).

1c- Decouple the negotiation of the standard packetization and the generic one by using [rid](https://tools.ietf.org/html/draft-ietf-mmusic-rid-15). This would be the more flexible but the most difficult to implement and specify.  This is the current one in the draft.

One point in favor for 1a) and 1b) is that we could reuse the same solution for audio, which I don't feel it is correctly handled right now.

**Comment by youennf** [comment]
> 1a.- Negotiate it associated to each payload type.

In theory, this allows to negotiate H264 with regular packetization but VP8 with generic one, or the reverse.
It seems we could go with an approach that applies to the whole m-section without losing much.

A slightly different approach is to use an attribute, say a=rtp-generic or a=rtpmap-generic.
An apt attribute could be added if per codec selection is thought useful.

Something like:
```
a=rtpmap:96 vp9/90000
a=rtpmap:97 vp8/90000
a=rtpmap:99 rtx/90000
a=rtp-generic
```

> 1b- Negotiate a single PT for the generic payload type and reference the original PT on the rtp packet.

I prototyped this one initially. I do not feel this is really compelling.
It seems better to me to have a payload type tied to some specific content and processing, which is my interpretation of the intent of payload type.
The packetization used is not changing the content nor really its processing (same decoder will be used whatever the packetization).

> 1c- Decouple the negotiation of the standard packetization and the generic one by using [rid](https://tools.ietf.org/html/draft-ietf-mmusic-rid-15). This would be the more flexible but the most difficult to implement and specify.

This could be rid or any other rtp header extension.
If we think the generic packetization requires usage of a rtp header extension, for instance to identify key frames, resolution and so on, the rtp header extension could also signal use of the generic depacketizer.

Agreed this allows great flexibility (sender chooses which packetizer, receiver follows). I am unsure of the use cases though...
In theory, this could match the flexibility provided by WebRTC insertable streams where an application can start with no transform, add a transform, stop the transform. Basically WebRTC insertable streams could select the packetization on a per frame basis.

If the RTP header extension is provided enough information and frame splitting is done right, I would hope that the use of the generic packetizer will not have downsides in terms of error resilience or other related aspects.
In that case, it seems a decision to use the generic packetizer at negotiation time might be the easiest approach.
Maybe there should be a section discussing the pros and cons of generic vs. codec specific packetizers.

> This is the current one in the draft.

The example in the current draft seems to be 1a.
Maybe I am misreading things.

> One point in favor for 1a) and 1b) is that we could reuse the same solution for audio, which I don't feel it is correctly handled right now.

How is it not correctly handled?
What would be the benefit to change audio?

**Comment by youennf** [comment]
> Maybe there should be a section discussing the pros and cons of generic vs. codec specific packetizers.

Filed https://github.com/murillo128/codec-agnostic-rtp-payload-format/issues/4

**Comment by murillo128** [comment]
The generic packetization and the standard packetization must have different PT for the same codec/format IMO, i doubt it would be accepted by the group otherwise.

There is a problem with the number of Payload Types. Currently in chrome there are 7 dynamic payload types for audio and more than 20 for video.  So we are reaching the maximum available ones, so we can't duplicate the number of PTs easily.

RID provides two interesting features:

- Allows to multiplex all codec formats within same PT (i.e. all h264 formats would use 1 PT)
- Allows to negotiate codec formats using an codec independent format.

Regarding audio, I don't think it is a good idea to not signal that the audio is encrypted on the SDP. So even if no new packetization format is needed, I would prefer to use the same negotiation/signaling for both audio/video.

**Comment by youennf** [comment]
> The generic packetization and the standard packetization must have different PT for the same codec/format IMO, i doubt it would be accepted by the group otherwise.

Maybe, though your suggestion to use RID is going in that direction.
This same principle would probably push against 1b.

Let's say we agree with this principle. Two questions then:
- Is there a need for an m-section to contain a PT for a given codec with standard packetization and another PT for the same codec with generic packetization?
- Is there a need for an m-section with some PT using standard packetization and some PT using generic packetization?

I do not clearly see a need for such flexibility.

A third question is:
- Is there a need to switch between standard and generic packetizations dynamically within the same PT (based for instance on RID)?

If we look at insertable streams API, an application could potentially start with no transform, hence make use of the standard packetization. But It could later start using a transform that may mandate the generic packetization. It might be nice to dynamically switch between the two.
My hope is that the application would negotiate the generic packetization up front and stick with it, in preparation of using the transform and since there would be no real downsides to using the generic packetization even without any transform.

Hence why an m-section switch seems good enough to me at the moment.
If both parties express they support the generic packetization, the generic packetization would be used.

> Regarding audio, I don't think it is a good idea to not signal that the audio is encrypted on the SDP.

AIUI, the question is:
- Should there be a way to express/negotiate transforms such as SFrame as part of the SDP?
The related questions would be:
- Is transform part of the codec? In which case, can we express usage of transform as a codec parameter?
- Should there be a way to know from the stream itself which transform to apply?
This seems like a separate discussion though. I'll open a new issue.

**Comment by youennf** [comment]
> * I'll open a new issue.

https://github.com/murillo128/codec-agnostic-rtp-payload-format/issues/6

**Comment by murillo128** [comment]
>Maybe, though your suggestion to use RID is going in that direction.
This same principle would probably push against 1b.

I mean that if the SDP has both vp8 (for example) with the standard packetization and the codec generic one they should use different PTs on the RTP packet so the sfu can decide if thy have to use the standard packetization/switching or not. Once we have an "unique" PT for the generic packetization, it doesn't matter what goes inside of the payload, as the sfu will not be able to inspect it anyway.

> Is there a need for an m-section to contain a PT for a given codec with standard packetization and another PT for the same codec with generic packetization?

It doesn't need to be a 1-to-1 relationship, but we can't sent something that is not following the standard packetization using a PT negotiated for it.

> Is there a need for an m-section with some PT using standard packetization and some PT using generic packetization?

No, but it is hard to restrict it at the SDP level.


> Is there a need to switch between standard and generic packetizations dynamically within the same PT (based for instance on RID)?

> If we look at insertable streams API, an application could potentially start with no transform, hence make use of the standard packetization. But It could later start using a transform that may mandate the generic packetization. It might be nice to dynamically switch between the two.

SFrame would not require it (I think the API should be stricter to ensure SFrame is always used) but the SFU must know which kind of payload it is going to receive, so having different PTs for the standard and the generic will allow this use case out of the box.

> My hope is that the application would negotiate the generic packetization up front and stick with it, in preparation of using the transform and since there would be no real downsides to using the generic packetization even without any transfo

The application can still do it, there is no restriction on how to the APP would choose when to use one packetization or the other.

> If both parties express they support the generic packetization, the generic packetization would be used.

Nothing prevents/forbids the app to behave that way, i don't think this is something we can enforce within this draft.


>Should there be a way to express/negotiate transforms such as SFrame as part of the SDP?

SFrame is e2e while the SDP negotiation is hoop by hoop, so I don't think the SFU should take part in negotiating SFrame at all. I

**Comment by youennf** [comment]
> Once we have an "unique" PT for the generic packetization, it doesn't matter what goes inside of the payload, as the sfu will not be able to inspect it anyway.

I am not sure I agree. The transform may be encryption but it could be something else.
Payload type to me identifies the format of the content, which is closer to compression format than to packetization format.

> Nothing prevents/forbids the app to behave that way, i don't think this is something we can enforce within this draft.

I am trying to identify the pros and cons of each approach, in terms of simplicity, flexibility and compatibility.
That is helpful to decide what seems the best approach.

For instance, the generic packetization can be selected at SDP negotiation time or can be identified as support through SDP but actually negotiated while sending media. I feel like the latter is not necessary, hence why I am not sure piggy backing on rid gains us much here.

So far, I am leaning towards something like: `a=rtp-generic` with an optional apt attribute when scoping down the generic packetization to a specific codec is required. The main benefits I see are compatibility and simplicity:
- Codec support is still represented by each rtpmap line. Removing one line here means removing codec support. Consistent with audio as well
- No additional PT cost
Do you see downsides to this approach or use cases that would be difficult to support?

**Comment by murillo128** [comment]
> Payload type to me identifies the format of the content, which is closer to compression format than to packetization format.

For me it is similar to RED, it has a single payload type even if the content can contain several codecs (with different PTs).

I don't like the  `a=rtp-generic`  mainly because i think that knowing if the content contains a standard packetization or the generic one is a "must have" feature and I don't think that the propossal will be very likely be accepted otherwise.

i agree that the `rid` usage, while having some nice properties, it is too cumbersome to implement and may be too risky. So I am happy to leave it just as potential solution, but discarded due to the implications.

**Comment by youennf** [comment]
OK, I'll try to summarise the various options in a PR (including RID) and the pros and cons.
I might add the fact there is consensus to that RID is probably too complex.

Let's continue discussing and trying to converge on which option to push for.

**Comment by murillo128** [comment]
would it be better to add the info on a different document (slides) that we could directly reuse to present at the ietf meetings? 
I don't think that info will be in final rfc, so i don't think that the editorial and merging work would be worth the effort.

**Comment by youennf** [comment]
> would it be better to add the info on a different document (slides) that we could directly reuse to present at the ietf meetings?

OK, I thought this draft was more informational, but slides seem fine as well.

**Comment by youennf** [comment]
> I don't like the `a=rtp-generic` mainly because i think that knowing if the content contains a standard packetization or the generic one is a "must have" feature and I don't think that the propossal will be very likely be accepted otherwise.

OK, I think I understand your point.

If 'a=rtp-generic' is in the SDP offer, and answerer does not want to use generic packetization (or does not know about it), this line will be dropped from the SDP answer. It will then be up to the offerer to decide whether the answer without 'a=rtp-generic' is ok or not. At that point, offerer and answerer should know whether generic packetization is used or not.

What you are saying is that this is not sufficient: the transmitted content should itself have the information it is using the generic packetization. One issue might be that the answerer will ignore the 'a=rtp-generic' line in the answer when building its payload type map but will keep it in the answer it will send back to the offerer. The offerer will send content, answerer will not be able to understand it and the error recovery mechanism might not kick in. Are there other potential issues?

In the case of having a generic payload type (per video codec or not), the payload type map would not include that payload type if the answerer does not understand the generic payload type. Not exactly sure what happens in case payload type is unknown and how the application would recover from that.

An alternative would be to create a RTP header extension that controls the use of the generic packetization.
This allows reusing SDP header extension negotiation and might also help https://github.com/murillo128/codec-agnostic-rtp-payload-format/issues/6.

**Comment by murillo128** [comment]
> What you are saying is that this is not sufficient: the transmitted content should itself have the information it is using the generic packetization. One issue might be that the answerer will ignore the 'a=rtp-generic' line in the answer when building its payload type map but will keep it in the answer it will send back to the offerer. The offerer will send content, answerer will not be able to understand it and the error recovery mechanism might not kick in. Are there other potential issues?

Yes, that is my concern. The sender may choose to send both codecs on the offer but it is not guaranteed in which format the RTP will finally be sent. You may decide to send normal h264 even if you just negotiate the generic packetization by default. The receiver must be able to tell for each RTP which packetization format is used.

> In the case of having a generic payload type (per video codec or not), the payload type map would not include that payload type if the answerer does not understand the generic payload type. Not exactly sure what happens in case payload type is unknown and how the application would recover from that.
> 

I guess this is inevitable, what happens if not all parties supports SFRAME? 

> An alternative would be to create a RTP header extension that controls the use of the generic packetization.

I don't like that approach, but I am open to discuss it on the slides in the avtcore meeting.

**Comment by youennf** [comment]
> I don't like that approach, but I am open to discuss it on the slides in the avtcore meeting.

I'd like to compare this approach with the header extension to provide the actual payload type.
I like the idea that a given payload type would stick to a single video decoder for instance.

**Comment by youennf** [comment]
Also, video/generic cannot really work without the RTP header extension to provide the APT.
On the contrary, if you do not negotiate the RTP header extension to dynamically negotiate generic packetizer, you simply cannot use the generic packetizer.

**Comment by murillo128** [comment]
should we close this issue?

**Comment by youennf** [comment]
Let's close it given we have the presentations and the document
