### ISSUE TITLE
RED handling

### ISSUE THREAD

**Issue by murillo128** [murillo128/codec-agnostic-rtp-payload-format#16]
Add clarifications regarding RED handling as it RED doesn't allow sending RTP header extensions for the redundant payloads.

The proposal is to only allow sending redundant payload with the same associated payload type as the primary RED content.

**Comment by youennf** [comment]
Also:
> RED is currently integrated as a codec in libwertc implementations.
> This makes transforms like SFrames be applied to the whole content of RED.
> One potential issue is that RED payload contains the payload type of the blocks.
> If the whole RED payload is end-to-end encrypted, the issue might be that the payload type of the end receiver is not matching the payload type of the sender. The SFU in the middle might not be able to dynamically update the media content.
> 
> I see at least two options:
> 
> Consider this as a limitation and it is up to the SFU to make sure to negotiate the same PT between sender and receiver
> Change the approach and consider that RED is applied after transform, in which case RED will concatenate transformed data and payload type can be changed by the SFU.
> This might be worth documenting in the draft.
