### ISSUE TITLE
Use AV1 packetizer as basis for generic packetizer?

### ISSUE THREAD

**Issue by youennf** [murillo128/codec-agnostic-rtp-payload-format#2]
As suggested by @murillo128, the AV1 packetizer is generic and could be used for other codecs as well.
This might require updating this spec to abstract it a bit from AV1 terminology.

Looking at what offers AV1 packetizer, it adds support fo fragmenting units in several packets, which is useful.
It also allows to aggregate units in a single packet.
One question is whether supporting aggregating units is worth it.

In the context of SFrame for instance, the whole frame is encrypted.
It might not be useful to aggregate units, or expose one frame as multiple units.
If we would like to have SFrame encrypt H.264 content except SPS/PPS, SFrame could potentially generate two units, one for SPS/PPS that would not be encrypted (key id= 0 maybe or decryptable by the SFU) and the other one that would be encrypted.
In that context, aggregating both units makes sense.

Having this ability could potentially have an impact on WebRTC insertable streams proposal in which case the unit fragmentation data could potentially be exposed and controlled by the web application.
I guess this could be used in the context of an application adding small metadata at the end of each frame which would then be useful for receiver to process the additional metadata.

I am wondering about other use cases.
Overall, it seems there could be some use for allowing to aggregate units.

**Comment by murillo128** [comment]
Note that I am not proposing to use the av1 packetizer, but the Dependency descriptor defined on the annex.

If we don't support aggregation or fragmentation units, the packetizer is trivial, basically nothing is required. Just split the frame blob in on or several packets.

Not sure exactly why you would need the SPS/PPS be sent in clear so the SFU can access their contents, but in that case, i think that a clearer solution would be to move them to an header extension

**Comment by youennf** [comment]
I see, I misunderstood what you were suggesting.
So your proposal is to use a barebone packetizer.
That seems the right approach and aligns with audio AFAICT.

> Not sure exactly why you would need the SPS/PPS be sent in clear so the SFU can access their contents, but in that case, i think that a clearer solution would be to move them to an header extension

SFU need sometimes information from SPS/PPS (profile, resolution).
It is unclear to me whether we would be good with just extracting some of the information from it and put this extracted information within a RTP header extension (generic or not).

**Comment by youennf** [comment]
Closing the issue now that the intent is clear to me.
