### ISSUE TITLE
How should be advertised transforms such as SFrame and/or insertable streams?

### ISSUE THREAD

**Issue by youennf** [murillo128/codec-agnostic-rtp-payload-format#6]
Currently, transforms such as SFrame or based on insertable streams are not signalled anywhere.
They are not signalled in SDP and are not signalled in the stream.
It is up to the application on both sides to know what is happening and do the signalling out of band.

Some questions:
- Should there be a way to express/negotiate transforms such as SFrame as part of the SDP?
- Should there be a way to know from the stream itself which transform to apply?
If we think so, it might be interesting to determine how we can model the transform, for instance:
- Is transform a subpart of the codec? Can we express usage of transform as a codec parameter?

**Comment by murillo128** [comment]
SFUs should not take part in the SFrame negotiation as per SFrame definition, it is an untrusted party.

**Comment by youennf** [comment]
> SFUs should not take part in the SFrame negotiation as per SFrame definition, it is an untrusted party.

Agreed the e2e negotiation is not really the business of the SFU.
The question is more whether it would be good for the SFU to know that the content is encrypted/transformed.
This does not seem required to me but you pointed out in https://github.com/murillo128/codec-agnostic-rtp-payload-format/issues/1#issuecomment-733996847:
> Regarding audio, I don't think it is a good idea to not signal that the audio is encrypted on the SDP.

**Comment by murillo128** [comment]
I think the SFU should know that the payload is encrypted/transformed, but not in which way it has been encrypted/transformed. So it is more an indication that "this a a black box/binary blob"  so the SFU does not try to parse the payload in any way.

Regarding audio, I have realized that I do inspect audio payload on the SFU, so I would need something similar to what we have in video. 

In particular, for OPUS, I check the TOC of the opus frame to know the audio frame length and be able to correctly set the timestamp in recording.  Also for recording, I was planning to extract in-band fec in case of packet losses and recreate previous frames as the players do not support PLC.

**Comment by murillo128** [comment]
should we close this issue?

**Comment by youennf** [comment]
Sure, the current document provides all necessary information I think.
